# Generated by Django 5.0.1 on 2024-02-18 18:39

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
                ('city_district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('DelivarPlace', models.CharField(max_length=10)),
                ('flexCheckDefault', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(choices=[('Skincare', 'Skincare'), ('Haircare', 'Haircare'), ('Oralcare', 'Oralcare')], max_length=20)),
                ('productCode', models.CharField(max_length=10, unique=True)),
                ('productName', models.CharField(max_length=40)),
                ('productBrand', models.CharField(max_length=40)),
                ('productReview', models.IntegerField()),
                ('packageQty', models.IntegerField()),
                ('oldPrice', models.IntegerField()),
                ('newPrice', models.IntegerField()),
                ('weight', models.CharField(choices=[('8g', '8 grams'), ('10g', '10 grams'), ('15g', '15 grams'), ('20g', '20 grams'), ('25g', '25 grams'), ('30g', '30 grams'), ('50g', '50 grams'), ('60g', '60 grams'), ('80g', '80 grams'), ('100g', '100 grams'), ('120g', '120 grams'), ('15ml', '15 milliliters'), ('20ml', '20 milliliters'), ('25ml', '25 milliliters'), ('50ml', '50 milliliters'), ('100ml', '100 milliliters')], max_length=20)),
                ('p_type', models.CharField(choices=[('Gel ', 'Gel '), ('Oil', 'Oil')], max_length=20)),
                ('trendingProduct', models.BooleanField(default=False)),
                ('popularProduct', models.BooleanField(default=False)),
                ('avalability', models.BooleanField(default=False)),
                ('favorite', models.BooleanField(default=False)),
                ('productBanner', models.ImageField(upload_to='product_banner_images/')),
                ('productImg1', models.ImageField(upload_to='product_images/')),
                ('productImg2', models.ImageField(upload_to='product_images/')),
                ('productImg3', models.ImageField(upload_to='product_images/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(max_length=10000)),
                ('benifits', ckeditor_uploader.fields.RichTextUploadingField(max_length=10000)),
                ('keyIngredients', ckeditor_uploader.fields.RichTextUploadingField(max_length=10000)),
                ('howToUse', ckeditor_uploader.fields.RichTextUploadingField(max_length=10000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Qty', models.IntegerField(default=0)),
                ('total_amt', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thaaragaiapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Qty', models.IntegerField(default=0)),
                ('product_price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thaaragaiapp.products')),
            ],
        ),
    ]
