# Generated by Django 5.0.1 on 2024-02-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaaragaiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productType',
            field=models.CharField(choices=[('Skincare', 'Skincare'), ('Haircare', 'Haircare'), ('Oralcare', 'Oralcare')], max_length=20),
        ),
    ]
