# Generated by Django 5.0.1 on 2024-02-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaaragaiapp', '0004_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_Qty',
            field=models.IntegerField(default=0),
        ),
    ]
