# Generated by Django 5.0.1 on 2024-02-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thaaragaiapp', '0006_cart_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
